routes/web.php
Route::get('/category/{slug}', 'Ecommerce\FrontController@categoryProduct')->name('front.category');
Route::get('/product/{slug}', 'Ecommerce\FrontController@show')->name('front.show_product');
//profile toko
Route::get('/toko/{username_toko}/{slug}', 'Ecommerce\FrontController@showtoko');
Route::post('cart', 'Ecommerce\CartController@addToCart')->name('front.cart');
Route::get('/cart', 'Ecommerce\CartController@listCart')->name('front.list_cart');
Route::post('/cart/update', 'Ecommerce\CartController@updateCart')->name('front.update_cart');

Route::get('/checkout/{toko}', 'Ecommerce\CartController@checkout')->name('front.checkout');
Route::post('/checkout', 'Ecommerce\CartController@processCheckout')->name('front.store_checkout');
Route::get('/checkout/{invoice}', 'Ecommerce\CartController@checkoutFinish')->name('front.finish_checkout');

Route::get('/kontak', 'Ecommerce\FrontController@kontak')->name('front.kontak');

Route::get('/artikel', 'ArtikelController@list_artikel')->name('artikel.list_artikel');
//Route::get('/artikel', 'ArtikelController@index')->name('artikel.index');
Route::get('/artikel/{blog_id}', 'ArtikelController@getFullPost')->name('post.read');

Route::get('/product/ref/{user}/{product}', 'Ecommerce\FrontController@referalProduct')->name('front.afiliasi');

Route::group(['prefix' => 'member', 'namespace' => 'Ecommerce'], function() {
    Route::get('login', 'LoginController@loginForm')->name('customer.login');
    Route::post('login', 'LoginController@login')->name('customer.post_login');
    Route::get('verify/{token}', 'FrontController@verifyCustomerRegistration')->name('customer.verify');

    Route::get('Register', 'RegisterController@registerForm')->name('customer.register');
    Route::post('Register', 'RegisterController@register')->name('customer.post_register');

    Route::group(['middleware' => 'customer'], function() {
        Route::get('dashboard', 'LoginController@dashboard')->name('customer.dashboard');
        Route::get('logout', 'LoginController@logout')->name('customer.logout');

        Route::post('/kontak/pesan', 'FrontController@addpesan')->name('front.addpesan');
        
        Route::get('/checkout', 'CartController@checkout')->name('front.checkout');
        Route::post('/checkout', 'CartController@processCheckout')->name('front.store_checkout');
        Route::get('/checkout/{invoice}', 'CartController@checkoutFinish')->name('front.finish_checkout');

        Route::get('orders', 'OrderController@index')->name('customer.orders');
        Route::get('orders/{invoice}', 'OrderController@view')->name('customer.view_order');
        Route::get('orders/pdf/{invoice}', 'OrderController@pdf')->name('customer.order_pdf');
        Route::post('orders/accept', 'OrderController@acceptOrder')->name('customer.order_accept');
        Route::get('orders/return/{invoice}', 'OrderController@returnForm')->name('customer.order_return');
        Route::put('orders/return/{invoice}', 'OrderController@processReturn')->name('customer.return');

        Route::get('payment/{invoice}', 'OrderController@paymentForm')->name('customer.paymentForm');
        Route::post('payment', 'OrderController@storePayment')->name('customer.savePayment');

        Route::get('setting', 'FrontController@customerSettingForm')->name('customer.settingForm');
        Route::post('setting', 'FrontController@customerUpdateProfile')->name('customer.setting');

        Route::get('/afiliasi', 'FrontController@listCommission')->name('customer.affiliate');

        Route::post('wishlist', 'FrontController@addTowishlist')->name('front.wishlist');
        Route::get('/wishlist', 'FrontController@wishlist')->name('front.list_wishlist');
        Route::post('/hapuswishlist', 'FrontController@deletewishlist')->name('front.delete_wishlist');

        //aktivasi toko
        Route::get('/aktivasitoko', 'FrontController@aktivasitoko')->name('customer.aktivasitoko');
        Route::post('/kirimaktivasi', 'FrontController@kirimaktivasi')->name('customer.kirimaktivasi');
        //tokosaya
        Route::resource('product', 'ProductController')->except(['show']);
        Route::get('/tokosaya', 'FrontController@tokosaya')->name('customer.tokosaya');
        Route::get('/profiletoko', 'FrontController@profiletoko')->name('customer.profiletoko');
        Route::post('profiletoko', 'FrontController@profiletokoUpdateProfile')->name('customer.profiletoko.update');
        Route::post('profiletoko/hapusava', 'FrontController@hapusava')->name('customer.profiletoko.hapusava');
        Route::post('profiletoko/uploudava', 'FrontController@uploadava')->name('customer.profiletoko.uploudava');
        Route::post('profiletoko/hapusbanner', 'FrontController@hapusbanner')->name('customer.profiletoko.hapusbanner');
        Route::post('profiletoko/uploudbanner', 'FrontController@uploadbanner')->name('customer.profiletoko.uploudbanner');
        Route::post('/aktifkantoko', 'FrontController@aktifkantoko')->name('customer.aktifkantoko');

        //bank
        Route::get('/tambahbank', 'FrontController@createbank')->name('customer.createbank');
        Route::post('/postbank', 'FrontController@storebank')->name('customer.storebank');
        Route::post('/hapusbank', 'FrontController@hapusbank')->name('customer.hapusbank');
        Route::get('/editbank/{id}', 'FrontController@editbank')->name('customer.editbank');
        Route::put('/updatebank/{id}', 'FrontController@updatebank')->name('customer.updatebank');



        //product cusomter
        Route::get('/tambahproduk', 'FrontController@createproduk')->name('customer.createproduk');
        Route::post('/postproduk', 'FrontController@storeproduk')->name('customer.storeproduk');
        Route::post('/hapusproduk', 'FrontController@hapusproduk')->name('customer.hapusproduk');
        Route::get('/editproduk/{id}', 'FrontController@editproduk')->name('customer.editproduk');
        Route::put('/updateproduk/{id}', 'FrontController@updateproduk')->name('customer.updateproduk');

        //product order
        Route::group(['prefix' => 'orderstoko'], function() {
            Route::get('/{invoice}', 'FrontController@view')->name('orderstoko.view');
            Route::get('/payment/{invoice}', 'FrontController@acceptPayment')->name('orderstoko.approve_payment');
            Route::post('/shipping', 'FrontController@shippingOrder')->name('orderstoko.shipping');
            Route::delete('/{id}', 'FrontController@destroy')->name('orderstoko.destroy');
            Route::get('/return/{invoice}', 'FrontController@return')->name('orderstoko.return');
            Route::post('/return', 'FrontController@approveReturn')->name('orderstoko.approve_return');
        });

        //laporan order
        Route::group(['prefix' => 'reportstoko'], function() {
            Route::get('/order/pdf/{daterange}', 'FrontController@orderReportPdf')->name('reportstoko.order_pdf');
            Route::get('/return/pdf/{daterange}', 'FrontController@returnReportPdf')->name('reportstoko.return_pdf');
        });

    });
});

Auth::routes();
//cara akses dashboard admin http://127.0.0.1:8000/login email : bungmohammad@gmail.com password : secret
Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('category', 'CategoryController')->except(['create', 'show']);
    Route::resource('product', 'ProductController')->except(['show']);
    Route::get('/product/bulk', 'ProductController@massUploadForm')->name('product.bulk');
    Route::post('/product/bulk', 'ProductController@massUpload')->name('product.saveBulk');
    Route::post('/product/marketplace', 'ProductController@uploadViaMarketplace')->name('product.marketplace');

    Route::get('/pesan', 'HomeController@pesan')->name('pesan');

    Route::get('/artikel', 'ArtikelController@index')->name('artikel.index');
    Route::get('/artikel/tambahartikel', 'ArtikelController@tambahartikel')->name('artikel.tambahartikel');
    Route::post('/artikel/store','ArtikelController@store')->name('artikel.store');
    Route::post('/artikel/hapusartikel', 'ArtikelController@hapusartikel')->name('artikel.hapusartikel');
    Route::get('/artikel/editartikel/{id}', 'ArtikelController@editartikel')->name('artikel.editartikel');
    Route::put('/artikel/updateartikel/{id}', 'ArtikelController@updateartikel')->name('artikel.updateartikel');

    Route::get('/aktivasitoko', 'AktivasiController@index')->name('aktivasitoko.index');
    Route::get('/aktivasitoko/detail/{id}', 'AktivasiController@detail')->name('aktivasitoko.detail');
    Route::post('/aktivasitoko/hapus', 'AktivasiController@hapus')->name('aktivasitoko.hapus');
    Route::post('/aktivasitoko/terima', 'AktivasiController@terima')->name('aktivasitoko.terima');
    Route::post('/aktivasitoko/tolak', 'AktivasiController@tolak')->name('aktivasitoko.tolak');

    Route::group(['prefix' => 'orders'], function() {
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('/{invoice}', 'OrderController@view')->name('orders.view');
        Route::get('/payment/{invoice}', 'OrderController@acceptPayment')->name('orders.approve_payment');
        Route::post('/shipping', 'OrderController@shippingOrder')->name('orders.shipping');
        Route::delete('/{id}', 'OrderController@destroy')->name('orders.destroy');
        Route::get('/return/{invoice}', 'OrderController@return')->name('orders.return');
        Route::post('/return', 'OrderController@approveReturn')->name('orders.approve_return');
    });

    Route::group(['prefix' => 'reports'], function() {
        Route::get('/order', 'HomeController@orderReport')->name('report.order');
        Route::get('/order/pdf/{daterange}', 'HomeController@orderReportPdf')->name('report.order_pdf');
        Route::get('/return', 'HomeController@returnReport')->name('report.return');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    protected $guarded = [];

    public function getStatusLabelAttribute()
    {
        if ($this->status == 0) {
            return '<span class="badge badge-secondary">Draft</span>';
        }
        return '<span class="badge badge-success">Aktif</span>';
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug($value); 
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

resources/views/ecommerce/tokosaya/orderstoko/return.blade.php
@extends('layouts.ecommerce')

@section('title')
    <title>Return - Pusat Belanja Online</title>
@endsection

@section('content')
    <!--================Home Banner Area =================-->
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="container">
            <div class="overlay"></div>
                <div class="banner_content text-center">
                    <h2>Return</h2>
                    <div class="page_link">
                        <a href="{{ url('/') }}">Home</a>
                        <a href="{{ route('customer.orders') }}">Return</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->


    <!--================Feature Product Area =================-->
    <section class="feature_product_area section_gap">
        <div class="main_box">
            <div class="container-fluid">
                <div class="animated fadeIn">
                    <div class="row">
                        <div class="col-md-3">
                            @include('layouts.ecommerce.module.sidebar')
                        </div>

                        <div class="col-md-9">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">
                                        Detail pesanan
                                    </h4>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <h4>Detail Pelanggan</h4>
                                            <table class="table table-bordered">
                                                <tr>
                                                    <th width="30%">Nama Pelanggan</th>
                                                    <td>{{ $order->customer_name }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Telp</th>
                                                    <td>{{ $order->customer_phone }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Alasan Return</th>
                                                    <td>{{ $order->return->reason }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Rekening Pengembalian Dana</th>
                                                    <td>{{ $order->return->refund_transfer }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Status</th>
                                                    <td>{!! $order->return->status_label !!}</td>
                                                </tr>
                                            </table>

                                            @if ($order->return->status == 0)
                                                <form action="{{ route('orderstoko.approve_return') }}" onsubmit="return confirm('Kamu Yakin?');" method="post">
                                                    @csrf
                                                    <div class="input-group mb-3">
                                                        <input type="hidden" name="order_id" value="{{ $order->id }}">
                                                        <select name="status" class="form-control" required>
                                                            <option value="">Pilih</option>
                                                            <option value="1">Terima</option>
                                                            <option value="2">Tolak</option>
                                                        </select>
                                                        <div class="input-group-prepend">
                                                            <button class="btn btn-primary btn-sm">Proses Return</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            @endif
                                        </div>
                                        <div class="col-md-6">
                                            <h4>Foto Barang Return</h4>
                                            <img src="{{ asset('storage/return/' . $order->return->photo) }}" class="img-responsive" height="200" alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Feature Product Area =================-->
@endsection

resources/views/ecommerce/tokosaya/orderstoko/view.blade.php
@extends('layouts.ecommerce')

@section('title')
    <title>Detail Pesanan - Re:market</title>
@endsection

@section('content')
	<!--================Home Banner Area =================-->
	<section class="banner_area">
		<div class="banner_inner d-flex align-items-center">
			<div class="container">
			<div class="overlay"></div>
				<div class="banner_content text-center">
					<h2>Detail Pesanan</h2>
					<div class="page_link">
						<a href="{{ url('/') }}">Home</a>
						<a href="{{ route('customer.orders') }}">Detail Pesanan</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Home Banner Area =================-->


	<!--================Feature Product Area =================-->
	<section class="feature_product_area section_gap">
		<div class="main_box">
			<div class="container-fluid">
				<div class="animated fadeIn">
					<div class="row">
						<div class="col-md-3">
							@include('layouts.ecommerce.module.sidebar')
						</div>

						<div class="col-md-9">
							<div class="card">
								<div class="card-header">
									<h4 class="card-title">
										Detail pesanan

										<div class="float-right">
											@if ($order->status == 1 && $order->payment->status == 0)
												<a href="{{ route('orderstoko.approve_payment', $order->invoice) }}" class="btn btn-primary btn-sm">Terima Pembayaran</a>
											@endif
										</div>
									</h4>
								</div>
								<div class="card-body">
									<div class="row">
										<div class="col-md-6">
											<h4>Detail Pelanggan</h4>
											<table class="table table-bordered">
												<tr>
													<th width="30%">Nama Pelanggan</th>
													<td>{{ $order->customer_name }}</td>
												</tr>
												<tr>
													<th>Telp</th>
													<td>{{ $order->customer_phone }}</td>
												</tr>
												<tr>
													<th>Alamat</th>
													<td>{{ $order->customer_address }} {{ $order->customer->district->name }} - {{  $order->customer->district->city->name}}, {{ $order->customer->district->city->province->name }}</td>
												</tr>
												<tr>
													<th>Order Status</th>
													<td>{!! $order->status_label !!}</td>
												</tr>
												@if ($order->status > 1)
													<tr>
														<th>Nomor Resi</th>
														<td>
															@if ($order->status == 2)
																<form action="{{ route('orderstoko.shipping') }}" method="post">
																	@csrf
																	<div class="input-group">
																		<input type="hidden" name="order_id" value="{{ $order->id }}">
																		<input type="text" name="tracking_number" placeholder="Masukkan Nomor Resi" class="form-control" required>
																		<div class="input-group-append">
																			<button class="btn btn-secondary" type="submit">Kirim</button>
																		</div>
																	</div>
																</form>
															@else
																{{ $order->tracking_number }}
															@endif
														</td>
													</tr>
												@endif
											</table>
										</div>
										<div class="col-md-6">
											<h4>Detail Pembayaran</h4>
											@if ($order->status != 0)
												<table class="table table-bordered">
													<tr>
														<th width="30%">Nama Pengirim</th>
														<td>{{ $order->payment->name }}</td>
													</tr>
													<tr>
														<th>Bank Tujuan</th>
														<td>{{ $order->payment->transfer_to }}</td>
													</tr>
													<tr>
														<th>Tanggal Transfer</th>
														<td>{{ $order->payment->transfer_date }}</td>
													</tr>
													<tr>
														<th>Bukti Pembayaran</th>
														<td><a target="_blank" href="{{ asset('storage/payment/' . $order->payment->proof) }}">Lihat</a></td>
													</tr>
													<tr>
														<th>Status</th>
														<td>{!! $order->payment->status_label !!}</td>
													</tr>
												</table>
											@else
												<h5 class="text-center">Belum Konfirmasi Pembayaran</h5>
											@endif
										</div>
										<div class="col-md-12">
											<h4>Detail Produk</h4>
											<table class="table table-borderd table-hover">
												<tr>
													<th>Produk</th>
													<th>Quantity</th>
													<th>Harga</th>
													<th>Berat</th>
													<th>Subtotal</th>
												</tr>
												@foreach ($order->details as $row)
													<tr>
														<td>{{ $row->product->name }}</td>
														<td>{{ $row->qty }}</td>
														<td>Rp {{ number_format($row->price) }}</td>
														<td>{{ $row->weight }} gr</td>
														<td>Rp {{ $row->qty * $row->price }}</td>
													</tr>
												@endforeach
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Feature Product Area =================-->
@endsection