routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Ecommerce\FrontController@index')->name('front.index');
Route::get('/product', 'Ecommerce\FrontController@product')->name('front.product');
Route::get('/product/sort', 'Ecommerce\FrontController@sort_product')->name('front.sort_product');
Route::get('/product/{slug}', 'Ecommerce\FrontController@show')->name('front.show_product');
Route::get('/category/{slug}', 'Ecommerce\FrontController@categoryProduct')->name('front.category');
Route::get('/product/{slug}', 'Ecommerce\FrontController@show')->name('front.show_product');
//profile toko
Route::get('/toko/{username_toko}/{slug}', 'Ecommerce\FrontController@showtoko');
Route::post('cart', 'Ecommerce\CartController@addToCart')->name('front.cart');
Route::get('/cart', 'Ecommerce\CartController@listCart')->name('front.list_cart');
Route::post('/cart/update', 'Ecommerce\CartController@updateCart')->name('front.update_cart');

Route::get('/checkout/{toko}', 'Ecommerce\CartController@checkout')->name('front.checkout');
Route::post('/checkout', 'Ecommerce\CartController@processCheckout')->name('front.store_checkout');
Route::get('/checkout/{invoice}', 'Ecommerce\CartController@checkoutFinish')->name('front.finish_checkout');

Route::get('/kontak', 'Ecommerce\FrontController@kontak')->name('front.kontak');

Route::get('/artikel', 'ArtikelController@list_artikel')->name('artikel.list_artikel');
//Route::get('/artikel', 'ArtikelController@index')->name('artikel.index');
Route::get('/artikel/{blog_id}', 'ArtikelController@getFullPost')->name('post.read');

Route::get('/product/ref/{user}/{product}', 'Ecommerce\FrontController@referalProduct')->name('front.afiliasi');

Route::group(['prefix' => 'member', 'namespace' => 'Ecommerce'], function() {
    Route::get('login', 'LoginController@loginForm')->name('customer.login');
    Route::post('login', 'LoginController@login')->name('customer.post_login');
    Route::get('verify/{token}', 'FrontController@verifyCustomerRegistration')->name('customer.verify');

    Route::get('Register', 'RegisterController@registerForm')->name('customer.register');
    Route::post('Register', 'RegisterController@register')->name('customer.post_register');

    Route::group(['middleware' => 'customer'], function() {
        Route::get('dashboard', 'LoginController@dashboard')->name('customer.dashboard');
        Route::get('logout', 'LoginController@logout')->name('customer.logout');

        Route::post('/kontak/pesan', 'FrontController@addpesan')->name('front.addpesan');
        
        Route::get('/checkout', 'CartController@checkout')->name('front.checkout');
        Route::post('/checkout', 'CartController@processCheckout')->name('front.store_checkout');
        Route::get('/checkout/{invoice}', 'CartController@checkoutFinish')->name('front.finish_checkout');

        Route::get('orders', 'OrderController@index')->name('customer.orders');
        Route::get('orders/{invoice}', 'OrderController@view')->name('customer.view_order');
        Route::get('orders/pdf/{invoice}', 'OrderController@pdf')->name('customer.order_pdf');
        Route::post('orders/accept', 'OrderController@acceptOrder')->name('customer.order_accept');
        Route::get('orders/return/{invoice}', 'OrderController@returnForm')->name('customer.order_return');
        Route::put('orders/return/{invoice}', 'OrderController@processReturn')->name('customer.return');

        Route::get('payment/{invoice}', 'OrderController@paymentForm')->name('customer.paymentForm');
        Route::post('payment', 'OrderController@storePayment')->name('customer.savePayment');

        Route::get('setting', 'FrontController@customerSettingForm')->name('customer.settingForm');
        Route::post('setting', 'FrontController@customerUpdateProfile')->name('customer.setting');

        Route::get('/afiliasi', 'FrontController@listCommission')->name('customer.affiliate');

        Route::post('wishlist', 'FrontController@addTowishlist')->name('front.wishlist');
        Route::get('/wishlist', 'FrontController@wishlist')->name('front.list_wishlist');
        Route::post('/hapuswishlist', 'FrontController@deletewishlist')->name('front.delete_wishlist');

        //aktivasi toko
        Route::get('/aktivasitoko', 'FrontController@aktivasitoko')->name('customer.aktivasitoko');
        Route::post('/kirimaktivasi', 'FrontController@kirimaktivasi')->name('customer.kirimaktivasi');
        //tokosaya
        Route::resource('product', 'ProductController')->except(['show']);
        Route::get('/tokosaya', 'FrontController@tokosaya')->name('customer.tokosaya');
        Route::get('/profiletoko', 'FrontController@profiletoko')->name('customer.profiletoko');
        Route::post('profiletoko', 'FrontController@profiletokoUpdateProfile')->name('customer.profiletoko.update');
        Route::post('profiletoko/hapusava', 'FrontController@hapusava')->name('customer.profiletoko.hapusava');
        Route::post('profiletoko/uploudava', 'FrontController@uploadava')->name('customer.profiletoko.uploudava');
        Route::post('profiletoko/hapusbanner', 'FrontController@hapusbanner')->name('customer.profiletoko.hapusbanner');
        Route::post('profiletoko/uploudbanner', 'FrontController@uploadbanner')->name('customer.profiletoko.uploudbanner');
        Route::post('/aktifkantoko', 'FrontController@aktifkantoko')->name('customer.aktifkantoko');

        //bank
        Route::get('/tambahbank', 'FrontController@createbank')->name('customer.createbank');
        Route::post('/postbank', 'FrontController@storebank')->name('customer.storebank');
        Route::post('/hapusbank', 'FrontController@hapusbank')->name('customer.hapusbank');
        Route::get('/editbank/{id}', 'FrontController@editbank')->name('customer.editbank');
        Route::put('/updatebank/{id}', 'FrontController@updatebank')->name('customer.updatebank');



        //product cusomter
        Route::get('/tambahproduk', 'FrontController@createproduk')->name('customer.createproduk');
        Route::post('/postproduk', 'FrontController@storeproduk')->name('customer.storeproduk');
        Route::post('/hapusproduk', 'FrontController@hapusproduk')->name('customer.hapusproduk');
        Route::get('/editproduk/{id}', 'FrontController@editproduk')->name('customer.editproduk');
        Route::put('/updateproduk/{id}', 'FrontController@updateproduk')->name('customer.updateproduk');

        //product order
        Route::group(['prefix' => 'orderstoko'], function() {
            Route::get('/{invoice}', 'FrontController@view')->name('orderstoko.view');
            Route::get('/payment/{invoice}', 'FrontController@acceptPayment')->name('orderstoko.approve_payment');
            Route::post('/shipping', 'FrontController@shippingOrder')->name('orderstoko.shipping');
            Route::delete('/{id}', 'FrontController@destroy')->name('orderstoko.destroy');
            Route::get('/return/{invoice}', 'FrontController@return')->name('orderstoko.return');
            Route::post('/return', 'FrontController@approveReturn')->name('orderstoko.approve_return');
        });

        //laporan order
        Route::group(['prefix' => 'reportstoko'], function() {
            Route::get('/order/pdf/{daterange}', 'FrontController@orderReportPdf')->name('reportstoko.order_pdf');
            Route::get('/return/pdf/{daterange}', 'FrontController@returnReportPdf')->name('reportstoko.return_pdf');
        });

    });
});

Auth::routes();
//cara akses dashboard admin http://127.0.0.1:8000/login email : bungmohammad@gmail.com password : secret
Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('category', 'CategoryController')->except(['create', 'show']);
    Route::resource('product', 'ProductController')->except(['show']);
    Route::get('/product/bulk', 'ProductController@massUploadForm')->name('product.bulk');
    Route::post('/product/bulk', 'ProductController@massUpload')->name('product.saveBulk');
    Route::post('/product/marketplace', 'ProductController@uploadViaMarketplace')->name('product.marketplace');

    Route::get('/pesan', 'HomeController@pesan')->name('pesan');

    Route::get('/artikel', 'ArtikelController@index')->name('artikel.index');
    Route::get('/artikel/tambahartikel', 'ArtikelController@tambahartikel')->name('artikel.tambahartikel');
    Route::post('/artikel/store','ArtikelController@store')->name('artikel.store');
    Route::post('/artikel/hapusartikel', 'ArtikelController@hapusartikel')->name('artikel.hapusartikel');
    Route::get('/artikel/editartikel/{id}', 'ArtikelController@editartikel')->name('artikel.editartikel');
    Route::put('/artikel/updateartikel/{id}', 'ArtikelController@updateartikel')->name('artikel.updateartikel');

    Route::get('/aktivasitoko', 'AktivasiController@index')->name('aktivasitoko.index');
    Route::get('/aktivasitoko/detail/{id}', 'AktivasiController@detail')->name('aktivasitoko.detail');
    Route::post('/aktivasitoko/hapus', 'AktivasiController@hapus')->name('aktivasitoko.hapus');
    Route::post('/aktivasitoko/terima', 'AktivasiController@terima')->name('aktivasitoko.terima');
    Route::post('/aktivasitoko/tolak', 'AktivasiController@tolak')->name('aktivasitoko.tolak');

    Route::group(['prefix' => 'orders'], function() {
        Route::get('/', 'OrderController@index')->name('orders.index');
        Route::get('/{invoice}', 'OrderController@view')->name('orders.view');
        Route::get('/payment/{invoice}', 'OrderController@acceptPayment')->name('orders.approve_payment');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    protected $fillable = ['name', 'parent_id', 'slug'];

    public function scopeGetParent($query)
    {
        return $query->whereNull('parent_id');
    }

    public function getNameAttribute($value)
    {
        return ucfirst($value);
    }

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug($value);
    }

    public function parent()
    {
        return $this->belongsTo(Category::class);
    }

    public function child()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }

    public function product()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    public function index()
    {
        $category = Category::with(['parent'])->orderBy('created_at', 'DESC')->paginate(10);
        $parent = Category::getParent()->orderBy('name', 'ASC')->get();
        return view('categories.index', compact('category', 'parent'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50|unique:categories'
        ]);

        $request->request->add(['slug' => $request->name]);
        Category::create($request->except('_token'));
        return redirect(route('category.index'))->with(['success' => 'Kategori Baru Ditambahkan!']);
    }

    public function edit($id)
    {
        $category = Category::find($id);
        $parent = Category::getParent()->orderBy('name', 'ASC')->get();
        return view('categories.edit', compact('category', 'parent'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|max:50|unique:categories,name,' . $id
        ]);

        $category = Category::find($id);
        $category->update([
            'name' => $request->name,
            'parent_id' => $request->parent_id
        ]);
        return redirect(route('category.index'))->with(['success' => 'Kategori Diperbaharui!']);
    }

    public function destroy($id)
    {
        $category = Category::withCount(['child', 'product'])->find($id);
        if ($category->child_count == 0 && $category->product_count == 0) {
            $category->delete();
            return redirect(route('category.index'))->with(['success' => 'Kategori Dihapus!']);
        }
        return redirect(route('category.index'))->with(['error' => 'Kategori Ini Memiliki Anak Kategori!']);
    }
}

resources/views/categories/edit.blade.php
@extends('layouts.admin')

@section('title')
    <title>Edit Kategori</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">Edit Kategori</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Edit Kategori</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('category.update', $category->id) }}" method="post">
                                @csrf
                                @method('PUT')
                                 
                                <div class="form-group">
                                    <label for="name">Kategori</label>
                                    <input type="text" name="name" class="form-control" value="{{ $category->name }}" required>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="parent_id">Kategori</label>
                                    <select name="parent_id" class="form-control">
                                        <option value="">None</option>
                                        @foreach ($parent as $row)
                                        <option value="{{ $row->id }}" {{ $category->parent_id == $row->id ? 'selected':'' }}>{{ $row->name }}</option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Simpan</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin')

@section('title')
    <title>Daftar Kategori</title>
@endsection

@section('content')
<main class="main">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Dashboard</li>
        <li class="breadcrumb-item active">Kategori</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Kategori Baru</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('category.store') }}" method="post">
                                @csrf
                                <div class="form-group">
                                    <label for="name">Kategori</label>
                                    <input type="text" name="name" class="form-control" required>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <label for="parent_id">Kategori</label>
                                    <select name="parent_id" class="form-control">
                                        <option value="">None</option>
                                        @foreach ($parent as $row)
                                        <option value="{{ $row->id }}">{{ $row->name }}</option>
                                        @endforeach
                                    </select>
                                    <p class="text-danger">{{ $errors->first('name') }}</p>
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary btn-sm">Tambah</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Daftar Kategori</h4>
                        </div>
                        <div class="card-body">
                            @if (session('success'))
                                <div class="alert alert-success">{{ session('success') }}</div>
                            @endif

                            @if (session('error'))
                                <div class="alert alert-danger">{{ session('error') }}</div>
                            @endif

                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Kategori</th>
                                            <th>Parent</th>
                                            <th>Created At</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($category as $val)
                                        <tr>
                                            <td></td>
                                            <td><strong>{{ $val->name }}</strong></td>
                                            <td>{{ $val->parent ? $val->parent->name:'-' }}</td>
                                            <td>{{ $val->created_at->format('d-m-Y') }}</td>
                                            <td>
                                                <form action="{{ route('category.destroy', $val->id) }}" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <a href="{{ route('category.edit', $val->id) }}" class="btn btn-warning btn-sm">Edit</a>
                                                    <button class="btn btn-danger btn-sm">Hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @empty
                                        <tr>
                                            <td colspan="5" class="text-center">Tidak ada data</td>
                                        </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                            {!! $category->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
@endsection